language: node_js
node_js:
  - 8
cache:
  - node_modules

notifications:
  slack: servirme:PL18rvrpG8M0tB8dTVhxAODI

script:
  - npm run lint
  - npm run test

#after_script:
#  - npm run send-coverage-data

#deploy:
#  provider: script
#  script: npm run deploy-prod
#  on:
#    branch: master

